-- Tabellen für X01
CREATE TABLE IF NOT EXISTS players_x01 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  average REAL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_x01 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_average REAL NOT NULL,
  leg_points INTEGER NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Foreign Key Definition (Constraint muss in einer separaten Zeile stehen, um das Parsen zu vereinfachen)
  FOREIGN KEY (player_id) REFERENCES players_x01 (id) ON DELETE CASCADE
);

-- Tabellen für Cricket
CREATE TABLE IF NOT EXISTS players_cricket (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  mpr REAL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_cricket (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_marks INTEGER NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players_cricket (id) ON DELETE CASCADE
);

-- Tabellen für Tactics
CREATE TABLE IF NOT EXISTS players_tactics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  mpr REAL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_tactics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_marks INTEGER NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players_tactics (id) ON DELETE CASCADE
);

-- Tabellen für ATC
CREATE TABLE IF NOT EXISTS players_atc (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  hit_rate REAL DEFAULT NULL, -- z.B. 0.7780 für 77.8%
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_atc (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_hit_rate REAL NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players_atc (id) ON DELETE CASCADE
);

-- Tabellen für Count Up
CREATE TABLE IF NOT EXISTS players_countup (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  ppr REAL DEFAULT NULL, -- Points Per Round
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_countup (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_points INTEGER NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players_countup (id) ON DELETE CASCADE
);

-- Tabellen für Segment Training
CREATE TABLE IF NOT EXISTS players_segment_training (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  is_registered INTEGER NOT NULL DEFAULT 0,
  hit_rate REAL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS games_history_segment_training (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player_id INTEGER NOT NULL,
  match_id TEXT NOT NULL,
  leg_number INTEGER NOT NULL,
  leg_hit_rate REAL NOT NULL,
  leg_darts INTEGER NOT NULL,
  finished_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (player_id) REFERENCES players_segment_training (id) ON DELETE CASCADE
);